

# This file was *autogenerated* from the file deneme.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_20 = Integer(20); _sage_const_15 = Integer(15); _sage_const_0p046 = RealNumber('0.046'); _sage_const_0p04 = RealNumber('0.04')
import sys
import os
import matplotlib.pyplot as plt

# Add the Algorithm directory to the Python path
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'Algorithm'))

# Now you can import Alg from the Algorithm directory
import Alg as cipher

sbox_hex = cipher.SBOX

# Convert to decimal
SBOX_DEC = [int(x) for x in sbox_hex]

S = SBox(SBOX_DEC)

def save_pollock(mat,
                 color_scheme="CMRmap_r",
                 file_name="pollock",
                 vmin=_sage_const_0 ,
                 vmax=_sage_const_20 ,
                 folder=None,
                 frame=True,
                 visible_axes=True,
                 colorbar=True,
                 file_type="png"):
    import matplotlib.pyplot as plt
    fig, p = plt.subplots(figsize=(_sage_const_15 ,_sage_const_15 ))
    if isinstance(mat, list):
        abs_mat = [[abs(mat[i][j]) for j in range(_sage_const_0 , len(mat[_sage_const_0 ]))]
                   for i in range(_sage_const_0 , len(mat))]
    else:
        abs_mat = [[abs(mat[i][j]) for j in range(_sage_const_0 , mat.ncols())]
                   for i in range(_sage_const_0 , mat.nrows())]
    axes = p.imshow(
        abs_mat,
        interpolation="none",
        cmap = plt.colormaps.get_cmap(color_scheme).resampled(int(_sage_const_100))
        vmin=vmin,
        vmax=vmax,
    )
    if colorbar:
        fig.colorbar(axes, orientation='vertical', fraction=_sage_const_0p046 , pad=_sage_const_0p04 )
    p.set_aspect('equal')
    p.get_xaxis().set_visible(visible_axes)
    p.get_yaxis().set_visible(visible_axes)
    p.patch.set_alpha(_sage_const_0 )
    p.set_frame_on(frame)
    if folder == None:
        name_base = "{}."+file_type
    else:
        name_base = folder + "/{}." + file_type
    fig.savefig(name_base.format(file_name))

def to_2d_list(lst, sublist_size):
    if sublist_size <= _sage_const_0 :
        raise ValueError("Sublist size must be greater than zero.")
    
    return [lst[i:i + sublist_size] for i in range(_sage_const_0 , len(lst), sublist_size)]

if __name__ == "__main__":
    
    
    save_pollock(S.difference_distribution_table())

