

# This file was *autogenerated* from the file SboxTest/sboxTest.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1p0 = RealNumber('1.0'); _sage_const_100 = Integer(100); _sage_const_32 = Integer(32); _sage_const_16 = Integer(16); _sage_const_6 = Integer(6); _sage_const_3 = Integer(3)
import sys
import os
# Add the utils directory to the Python path
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'utils'))
# Add the Algorithm directory to the Python path
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'Algorithm'))

# Now you can import Alg from the Algorithm directory
import Alg as cipher
from sage.crypto.sbox import SBox
from PIL import Image
import utils

root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
results_dir = os.path.join(root_dir, 'Results')
os.makedirs(results_dir, exist_ok=True)

sbox_hex = cipher.SBOX

# Convert to decimal
SBOX_DEC = [int(x) for x in sbox_hex]

S = SBox(SBOX_DEC)


# Check if the S-box is 1-1 (bijective)
def is_one_to_one(sbox):
    # Create a set of unique outputs
    unique_outputs = set(sbox)
    return len(unique_outputs) == len(sbox)

print("S is 1-1:", is_one_to_one(SBOX_DEC))  
# Purpose: Verify that every input maps to a unique output.
# Significance: A bijective S-box is necessary for ensuring reversibility in block cipher operations.
# Expected: True for cryptographically secure S-boxes.

# 1. Check if the S-box has a linear structure (weakness if True)
print("S is linear: ", S.has_linear_structure())  
# Purpose: Verify if the S-box is linear. 
# Significance: Linear S-boxes are insecure as they can be expressed as a linear function. 
# Expected: False.

# 2. Check if the S-box is balanced
print("S is balanced: ", S.is_balanced())  
# Purpose: Check if each output value occurs equally often.
# Significance: Balanced S-boxes ensure uniform output distribution, essential for security.
# Expected: True.

# 3. Find fixed points of the S-box (S(x) = x)
print("Fixed points of S:", S.fixed_points())  
# Purpose: Identify inputs that map to themselves.
# Significance: Fixed points can lead to cryptographic weaknesses.
# Expected: Few or no fixed points.

# 4. Check if the S-box is Almost Perfect Nonlinear (APN)
print("S is APN: ", S.is_almost_bent())  
# Purpose: Verify resistance to differential cryptanalysis.
# Significance: APN S-boxes are optimal for this purpose.
# Expected: True for optimal S-boxes. Rarely happen in block ciphers.

# 5. Check if the S-box is bent
print("S is bent: ", S.is_bent())  
# Purpose: Verify if the S-box has maximal non-linearity.
# Significance: Bent S-boxes resist linear cryptanalysis exceptionally well.
# Expected: False (most block cipher S-boxes are not strictly bent).

print("S is almost bent: ", S.is_almost_bent())

# 6. Check if the S-box is an involution (S(S(x)) = x)
print("S is involution: ", S.is_involution())  
# Purpose: Verify if encryption and decryption use the same S-box.
# Significance: Involutory S-boxes simplify implementation.
# Expected: Depends on the S-box design.


print("Nonlinearity of S:", S.nonlinearity())

# 8. Maximal algebraic degree of the S-box
print("Maximal algebraic degree of all its component functions:", S.max_degree())  
# Purpose: Evaluate the highest degree of the S-box's Boolean functions.
# Significance: High degree ensures non-linearity and resistance to attacks.
# Expected: Close to n-1 for an n-bit S-box.

# 9. Minimal algebraic degree of the S-box
print("Minimal algebraic degree of all its component functions:", S.min_degree())  
# Purpose: Find the lowest algebraic degree among the component functions.
# Significance: Low degree might indicate weaknesses.
# Expected: Reasonably high value.

# 10. Maximal value in the Difference Distribution Table (DDT)
print("Max value in DDT:", S.differential_uniformity())  
# Purpose: Evaluate resistance to differential cryptanalysis.
# Significance: Lower values indicate stronger resistance.
# Expected: Small value (ideal is 2^(n-2)).

# 11. Maximal value in the Linear Approximation Table (LAT)
print("Max value in LAT:", S.linear_branch_number())  
# Purpose: Measure resistance to linear cryptanalysis.
# Significance: High branch numbers ensure better diffusion.
# Expected: High value.

# 12. Maximal value in the Boomerang Connectivity Table (BCT)
print("Max value in BCT:", S.boomerang_uniformity())  
# Purpose: Evaluate resistance to boomerang attacks.
# Significance: Lower values are better.
# Expected: Small value.

# 13. Branch number of the S-box
print("Branch number of S:", S.differential_branch_number())  
# Purpose: Evaluate the minimum number of active S-boxes in differential propagation.
# Significance: High branch number ensures good diffusion.
# Expected: High value.

# Convert the S-box to a permutation (adjusting for 0-based to 1-based indexing)
perm = Permutation([x + _sage_const_1  for x in SBOX_DEC])

# Get the cycles of the permutation
cycles = perm.to_cycles()

# Print the number of cycles and their lengths
print("Number of cycles and cycle lengths:", len(cycles),",", [len(cycle) for cycle in cycles])

print("Cycles in S :", cycles)

# Additional S-box Tests

# 14. Strict Avalanche Criterion (SAC)
def strict_avalanche_criterion(sbox):
    """Check SAC for each input bit position"""
    n = sbox.input_size()
    m = sbox.output_size()
    sac_matrix = []
    for i in range(n):  # input bit position
        row = []
        for j in range(m):  # output bit position
            # Count transitions when flipping input bit i
            transitions = _sage_const_0 
            for x in range(_sage_const_2 **n):
                x_flipped = x ** (_sage_const_1  << i)
                if x_flipped >= _sage_const_2 **n:  # Ensure valid input
                    continue
                out_orig = sbox[x]
                out_flipped = sbox[x_flipped]
                if ((out_orig >> j) & _sage_const_1 ) != ((out_flipped >> j) & _sage_const_1 ):
                    transitions += _sage_const_1 
            probability = transitions / (_sage_const_2 **n)
            row.append(probability)
        sac_matrix.append(row)
    return sac_matrix

print("\n##### Strict Avalanche Criterion (SAC) #####")
sac_results = strict_avalanche_criterion(S)
for i, row in enumerate(sac_results):
    print(f"Input bit {i}: {['{:.3f}'.format(float(x)) for x in row]}")
# Purpose: Tests if flipping one input bit changes each output bit with probability 0.5
# Significance: SAC ensures good diffusion properties
# Expected: Values close to 0.5

# 15. Bit Independence Criterion (BIC)
def bit_independence_criterion(sbox):
    """Check if output bits are independent"""
    n = sbox.input_size()
    m = sbox.output_size()
    bic_matrix = []
    for i in range(m):
        row = []
        for j in range(m):
            if i == j:
                row.append(_sage_const_1p0 )  # Self-correlation is 1
                continue
            correlation = _sage_const_0 
            for x in range(_sage_const_2 **n):
                bit_i = (sbox[x] >> i) & _sage_const_1 
                bit_j = (sbox[x] >> j) & _sage_const_1 
                correlation += (-_sage_const_1 )**(bit_i ** bit_j)
            correlation /= (_sage_const_2 **n)
            row.append(abs(correlation))
        bic_matrix.append(row)
    return bic_matrix

print("\n##### Bit Independence Criterion (BIC) #####")
bic_results = bit_independence_criterion(S)
for i, row in enumerate(bic_results):
    print(f"Output bit {i}: {['{:.3f}'.format(float(x)) for x in row]}")
# Purpose: Verifies that output bits are pairwise independent
# Significance: Ensures no linear dependencies between output bits
# Expected: Off-diagonal values close to 0

# 16. Algebraic Immunity
def algebraic_immunity(sbox):
    """Calculate algebraic immunity of the S-box"""
    n = sbox.input_size()
    immunity = n  # Start with maximum possible
    
    # Check all possible low-degree annihilators
    for degree in range(_sage_const_1 , n//_sage_const_2  + _sage_const_1 ):
        found_annihilator = False
        # Check component functions
        for output_bit in range(sbox.output_size()):
            component = sbox.component_function(output_bit)
            if component.algebraic_degree() <= degree:
                found_annihilator = True
                break
        if found_annihilator:
            immunity = degree
            break
    
    return immunity

print("\nAlgebraic immunity of S:", algebraic_immunity(S))
# Purpose: Measures resistance to algebraic attacks
# Significance: Higher immunity means better resistance to algebraic cryptanalysis
# Expected: At least 2 for secure S-boxes

# 17. Component Function Analysis
def analyze_component_functions(sbox):
    """Analyze each component function of the S-box"""
    results = {}
    for i in range(sbox.output_size()):
        component = sbox.component_function(i)
        results[f'bit_{i}'] = {
            'algebraic_degree': component.algebraic_degree(),
            'nonlinearity': component.nonlinearity(),
            'truth_table': component.truth_table()
        }
    return results

print("\n##### Component Function Analysis #####")
component_analysis = analyze_component_functions(S)
for bit, props in component_analysis.items():
    print(f"{bit}: degree={props['algebraic_degree']}, nonlinearity={props['nonlinearity']}")
# Purpose: Detailed analysis of each output bit's Boolean function
# Significance: Identifies potential weaknesses in individual bit functions

# 18. Distance to Random S-boxes
def distance_to_random(sbox, samples=_sage_const_100 ):
    """Calculate distance to random S-boxes"""
    import numpy as np
    
    n = sbox.input_size()
    distances = []
    
    for _ in range(samples):
        # Generate random permutation
        random_perm = list(range(_sage_const_2 **n))
        np.random.shuffle(random_perm)
        random_sbox = SBox(random_perm)
        
        # Calculate distance metric (difference in nonlinearity)
        dist = abs(sbox.nonlinearity() - random_sbox.nonlinearity())
        distances.append(dist)
    
    return {
        'mean_distance': np.mean(distances),
        'std_distance': np.std(distances),
        'min_distance': min(distances),
        'max_distance': max(distances)
    }

print("\n##### Distance to Random S-boxes #####")
random_dist = distance_to_random(S)
print(f"Mean distance: {float(random_dist['mean_distance']):.3f}")
print(f"Std distance: {float(random_dist['std_distance']):.3f}")
print(f"Min distance: {float(random_dist['min_distance']):.3f}")
print(f"Max distance: {float(random_dist['max_distance']):.3f}")
# Purpose: Measures how 'random' the S-box appears
# Significance: Closer to random is generally better for security

# 19. Higher-Order Differential Uniformity
def higher_order_differential_uniformity(sbox, order=_sage_const_2 ):
    """Calculate higher-order differential uniformity"""
    n = sbox.input_size()
    max_count = _sage_const_0 
    
    # Simplified implementation - check derivative uniformity
    for mask in range(_sage_const_1 , min(_sage_const_2 **n, _sage_const_32 )):  # Limit for performance
        derivative_sbox = sbox.derivative(mask)
        # Count frequency of each output difference
        diff_counts = {}
        for x in range(_sage_const_2 **n):
            diff = derivative_sbox[x]
            diff_counts[diff] = diff_counts.get(diff, _sage_const_0 ) + _sage_const_1 
        if diff_counts:
            max_count = max(max_count, max(diff_counts.values()))
    
    return max_count

print("\nHigher-order differential uniformity of S:", higher_order_differential_uniformity(S))
# Purpose: Resistance to higher-order differential attacks
# Significance: Lower values indicate better resistance

# 20. Detailed Cycle Analysis
def detailed_cycle_analysis(sbox):
    """Detailed analysis of cycle structure"""
    perm = Permutation([x + _sage_const_1  for x in sbox])
    cycles = perm.to_cycles()
    
    analysis = {
        'num_cycles': len(cycles),
        'cycle_lengths': [len(c) for c in cycles],
        'max_cycle_length': max(len(c) for c in cycles) if cycles else _sage_const_0 ,
        'fixed_points': sum(_sage_const_1  for c in cycles if len(c) == _sage_const_1 ),
        'transpositions': sum(_sage_const_1  for c in cycles if len(c) == _sage_const_2 ),
        'cycle_length_distribution': {}
    }
    
    for length in set(analysis['cycle_lengths']):
        analysis['cycle_length_distribution'][length] = analysis['cycle_lengths'].count(length)
    
    return analysis

print("\n##### Detailed Cycle Analysis #####")
cycle_analysis = detailed_cycle_analysis(S)
print(f"Number of cycles: {cycle_analysis['num_cycles']}")
print(f"Maximum cycle length: {cycle_analysis['max_cycle_length']}")
print(f"Fixed points: {cycle_analysis['fixed_points']}")
print(f"Transpositions: {cycle_analysis['transpositions']}")
print(f"Cycle length distribution: {cycle_analysis['cycle_length_distribution']}")
# Purpose: Detailed analysis of permutation cycle structure
# Significance: Cycle structure affects diffusion properties

# Helper function to display tables with detailed formatting
def pretty_table(matrix, label, max_size=_sage_const_16 ):
    nrows, ncols = matrix.nrows(), matrix.ncols()
    print(f"\n##### {label} #####")
    
    # Print column headers
    header = ["{:>5}".format(i) for i in range(min(max_size, ncols))]
    print("     " + " ".join(header) + (" ..." if ncols > max_size else ""))
    print("    " + "-" * (min(max_size, ncols) * _sage_const_6  + (_sage_const_3  if ncols > max_size else _sage_const_0 )))
    
    # Print rows with indices
    for row_index in range(min(max_size, nrows)):
        row = matrix.row(row_index)
        formatted_row = " ".join(
            "{:>5}".format(int(x)) if x in ZZ else "{:>5.2f}".format(float(x)) for x in row[:max_size]
        )
        print(f"{row_index:>3} | {formatted_row}" + (" ..." if ncols > max_size else ""))
    
    # Indicate if rows are truncated
    if nrows > max_size:
        print("...")



# Display formatted tables
pretty_table(S.difference_distribution_table(), "Difference Distribution Table (DDT)")
pretty_table(S.linear_approximation_table(), "Linear Approximation Table (LAT)")
pretty_table(S.boomerang_connectivity_table(), "Boomerang Connectivity Table (BCT)")
pretty_table(S.autocorrelation_table(), "Autocorrelation Table (ACT)")


#f2 = S.component_function(3)
#print(f2.algebraic_normal_form() )        

#print(S.interpolation_polynomial())

#print(S.difference_distribution_table())




# Convert SageMath matrix to a list of lists
data = [list(row) for row in S.difference_distribution_table().rows()]
img = utils.create_image_from_2d_list(data)
#img.show()
img.save(os.path.join(results_dir, "DDT.png"))

# Convert SageMath matrix to a list of lists
data = [list(row) for row in S.boomerang_connectivity_table().rows()]
img = utils.create_image_from_2d_list(data)
#img.show()
img.save(os.path.join(results_dir, "BCT.png"))


